# Change these first
owner: gpcaretti # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
delay: 1500 # 1.5 seconds - delay that will occur between checking each configured endpoint

sites:
  - name: GP software
    url: https://gpsoftware.it
  - name: PiP
    url: https://www.portamiinpista.it
    maxResponseTime: 8000
  - name: PiP test 200
    url: https://www.portamiinpista.it
    expectedStatusCodes:
      - 200
- name: Juris
    url: https://www.jurisweb.it

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
